# Generated by Django 3.1.3 on 2021-06-12 20:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=500, unique=True)),
                ('firstname', models.CharField(blank=True, max_length=30, verbose_name='Firstname')),
                ('lastname', models.CharField(blank=True, max_length=30, verbose_name='Lastname')),
                ('email', models.EmailField(max_length=90, unique=True, verbose_name='Email')),
                ('user_phone', models.CharField(max_length=15, null=True, unique=True, verbose_name='Telephone number')),
                ('user_gender', models.CharField(max_length=15, verbose_name='Gender')),
                ('user_password', models.TextField(max_length=200, verbose_name='Password')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('role', models.TextField(default='user', max_length=50, verbose_name='User role')),
            ],
            options={
                'db_table': 'CIT_USER_TABLE',
            },
        ),
    ]
