# Generated by Django 3.1.3 on 2021-06-12 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_code',
            field=models.TextField(default='', max_length=20, verbose_name='Reset Code'),
        ),
    ]
